# Generated by Django 2.1.4 on 2018-12-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startx', '0002_auto_20181224_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('patient_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
