# Generated by Django 2.1.4 on 2018-12-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startx', '0005_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
