# Generated by Django 2.1.4 on 2019-01-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startx', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
