# Generated by Django 2.1.4 on 2019-01-13 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startx', '0009_auto_20190109_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
    ]
