# Generated by Django 2.1.4 on 2019-01-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startx', '0020_auto_20190126_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
