# Generated by Django 2.1.4 on 2019-02-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startx', '0022_auto_20190127_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='contact_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='duration',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
