# Generated by Django 2.1.4 on 2019-02-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startx', '0023_auto_20190208_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='city',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
